title: "Jamie 的极客小屋"
description: "记录思考、分享技术、探索未来。"
author: "Jamie Hull"
language: "zh-CN"
theme: null
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
timezone: Asia/Shanghai
url: "https://你的用户名.github.io"
baseurl: ""
nav:
  - name: 首页
    link: /
  - name: 关于
    link: /about
