title: "JIN 的极客宇宙"
description: "记录技术、思考与创作。"
author: "JIN"
language: "zh-CN"
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
timezone: Asia/Shanghai
url: "https://jin-cyber-wq.github.io"
baseurl: ""

nav:
  - name: 首页
    link: /
  - name: 关于
    link: /about
