title: "JIN 的极客宇宙"
description   描述: "记录技术、思考与创作。"
author   作者: "JIN"
language   语言: "zh-CN"   “应用”   “应用”   “应用”
markdown   减价: kramdown   减价:kramdown
highlighter   萤光笔: rouge   萤光笔:胭脂
permalink   永久链接: /永久链接:/年/月/:/ /天:标题:year/:month/:day/:title/
timezone   时区: Asia/Shanghai   时区:亚洲/上海
url: "https://jin-cyber-wq.github.io"
baseurl: ""

nav:
  - name   名字: 首页
    link   链接: /   链接:/
  - name   名字: 关于
    link   链接: /about   链接:/
